### ISSUE TITLE
Add CI status check on PR

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/application-insights-connector#32]

**Comment by tomkerkhove** [comment]
Tested a bit around with #33, #34 & #35 - Looks like VSTS is unable to create the webhook on new PRs while in a new repo it works fine.

**Comment by samneirinck** [comment]
Time to change to Travis or AppVeyor? That way the build details are public as well.

**Comment by tomkerkhove** [comment]
Good suggestion @samneirinck, I'm switching to AppVeyor
