### ISSUE TITLE
API should return 500 when no instrumentation key is specified

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/application-insights-connector#39]
API should return 500 when no instrumentation key is specified.

This means that if no instrumentation key was specified in the request nor a default one configured, that the API should return an HTTP 500 Internal Server Error.

**Comment by MassimoC** [comment]
it should be 400 bad request when in the request, 500 when a default one is configured

**Comment by tomkerkhove** [comment]
Actually it should be like this - If neither the payload nor configuration file contains one it should return a 500.

It's ok if the payload doesn't contain an instrumention key as it's optional, as long as it has a default configuration on the API itself, because of this there won't be a 400?.

To summarize:
✔️ Nothing in payload but default configured on API  
✔️ Payload & configuration contain telemetry, payload version used  
❌  Nothing in payload nor in configuration on API  (HTTP 500)

Would that make sense?

**Comment by MassimoC** [comment]
yes :)
