### ISSUE TITLE
Application Insight resource is showing connected to the OMS workspace which is already been deleted 2 month ago.

### ISSUE THREAD

**Issue by sid326** [CoditEU/application-insights-connector#43]
I have connected my application insights resource to the log Analytics OMS workspace using
log-analytics-app-insights-connector. After testing I have deleted the OMS workspace But when I again tried to connect that application insight resource to another OMS workspace its showing that it is already connected to some other workspace( Previous workspace which was deleted 2 months back). Why it is showing that it is already connected to the workspace when that workspace is deleted.?? Can anyone please help with this. 

![image](https://user-images.githubusercontent.com/11275940/37328176-2f046af6-26bf-11e8-8b8a-456a3d20f82e.png)

**Comment by tomkerkhove** [comment]
I think you should open an issue on the OMS/Application Insights side given this API App only integrates with an Application Insights instance and does not manage it

**Comment by sid326** [comment]
sorry I have opened that in another tab and because of confusion I have posted here. I will delete that sorry for the trouble.

**Comment by tomkerkhove** [comment]
No problem at all, I hope your issue gets resolved. Closing this issue on your request.
